name: Питомник немецких овчарок «Фонте Фиделити» г. Тольятти
url: https://fontefideliti.ru
collections:
  shows:
    permalink: /shows/:name.htm
    output: true
sass:
  style: compressed
compress_html:
  clippings: all
