encoding: utf-8
exclude:
  - LICENSE
  - README.md
url: https://fontefideliti.ru

collections:
  shows:
    permalink: /shows/:name.htm
    output: true
  perdog_cards:
    permalink: /:categories/:name/index.htm
    output: true

defaults:
  - scope:
      type: perdog_cards
    values:
      layout: dog_index

sass:
  style: compressed

compress_html:
  clippings: all

plugins:
  - jekyll-redirect-from
