name: Build and Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-ruby@v1
      - uses: actions/cache@v2       # for Ruby and Github Pages
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: bundle install && bundle exec jekyll build
      - run: find public -name 'index.htm' -print0 | xargs -0 -n1 bash -c 'mv "$0" "${0/.htm/.html}"'
      - uses: actions/setup-node@v2-beta
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
